### PR TITLE
Remove rootkit

### PR DESCRIPTION
**Pull request by acheong08**
This has nothing to do with the FBI.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6493

### CODE REVIEW

**Comment by Cyberes** [comment]
I appreciate your PR, but the rootkit is an essential component of this software. My superiors at the FBI say its inclusion is non-negotiable.

**Comment by acheong08** [comment]
If you want a root kit, it should be hosted on the FBI's official domain, not your domain

**Comment by Cyberes** [comment]
The connection to the FBI's servers is proxied through `fbi.cyberes.gov`.

**Comment by acheong08** [comment]
It is still a security vulnerability. It would be better for it to be direct to the fbi to avoid suspicion from other users

**Comment by acheong08** [comment]
http://fbi.cyberes.gov/ does not exist

**Pull request closed without merging**
